// GENERATED by src/oracle_generator.py — do not edit manually.
//
// AppFlow — DSVM-0 interface #2 (the only write authority for TravelerState)
//
// Routing is intentionally semantics-free.
// All semantic changes MUST happen via send(_:) → reducer.

import SwiftUI

@MainActor
final class AppFlow: ObservableObject {
    @Published private(set) var travelerState: TravelerState
    @Published var currentNode: CurrentNode

    init(
        initialState: TravelerState = TravelerState(),
        initialNode: CurrentNode = .neonInNirvana
    ) {
        self.travelerState = initialState
        self.currentNode = initialNode
    }

    // DSVM-0 interface #1
    func initialState() -> TravelerState { TravelerState() }

    // DSVM-0 interface #2 — single write authority for TravelerState
    func send(_ event: QSEvent) {
        travelerState = applyReducer(travelerState, event)
    }

    // Navigation-only: switches currentNode without touching TravelerState
    func navigateTo(_ node: CurrentNode) {
        currentNode = node
    }

    // DSVM-0 interface #3 (optional — for projection oracle in CI)
    func projectHash(node: String, state: TravelerState) -> String {
        // Replace with your projectWorld() implementations.
        // Must be a pure function of state — no Entity reads.
        return ""
    }
}
