// GENERATED by src/oracle_generator.py — do not edit manually.
//
// AppNavigator — pure projection selector
//
// Navigation is a pure selection of projection, not a causality step.
// The only causality step remains: send(event) → reducer → new TravelerState.

import SwiftUI

struct AppNavigator: View {
    @EnvironmentObject private var appFlow: AppFlow

    var body: some View {
        switch appFlow.currentNode {
        case .neonInNirvana:
            NeonInNirvanaView(
                travelerState: appFlow.travelerState,
                send: appFlow.send,
                navigateTo: appFlow.navigateTo
            )
        case .godlyDNA:
            GodlyDNAView(
                travelerState: appFlow.travelerState,
                send: appFlow.send,
                navigateTo: appFlow.navigateTo
            )
        case .skyHigh:
            SkyHighView(
                travelerState: appFlow.travelerState,
                send: appFlow.send,
                navigateTo: appFlow.navigateTo
            )
        }
    }
}

enum CurrentNode: String, Equatable {
    case neonInNirvana = "neon-in-nirvana"
    case godlyDNA      = "godly-dna"
    case skyHigh       = "sky-high"
}

// MARK: - Minimal view signatures
// Views receive TravelerState as a value and can only call send(event).
// They must not mutate TravelerState directly.

struct NeonInNirvanaView: View {
    let travelerState: TravelerState
    let send: (QSEvent) -> Void
    let navigateTo: (CurrentNode) -> Void

    var body: some View {
        // Wire your existing NeonInNirvanaView content here.
        // Example: Button("Enter Godly DNA") {
        //     send(.onNodeCompleted(nodeId: "neon-in-nirvana"))
        //     navigateTo(.godlyDNA)
        // }
        Text("Node A: Neon In Nirvana")
    }
}

struct GodlyDNAView: View {
    let travelerState: TravelerState
    let send: (QSEvent) -> Void
    let navigateTo: (CurrentNode) -> Void

    var body: some View {
        // Wire your existing GodlyDNAView content here.
        // Branch choice example:
        // Button("Ascend") { send(.onChoiceAscension); navigateTo(.skyHigh) }
        // Button("Create") { send(.onChoiceCreation); navigateTo(.skyHigh) }
        Text("Node B: Godly DNA")
    }
}

struct SkyHighView: View {
    let travelerState: TravelerState
    let send: (QSEvent) -> Void
    let navigateTo: (CurrentNode) -> Void

    var body: some View {
        // Wire your existing SkyHighView content here.
        // Temporal drift: projectWorld() reads travelerState, never scene state.
        Text("Node C: Sky High")
    }
}
