#!/usr/bin/env bash
# audit_dsvm.sh — DSVM-0 Pre-Compilation Causality Gate (Phase 1 of CI pipeline)
#
# This is NOT a utility script.  It is a pre-test causality gate.
# It sits above Swift, below CI, and decides whether the system is even
# allowed to become a testable object.
#
# If this script fails → nothing else executes.
#
# Generated by src/oracle_generator.py — do not edit manually.
# File-role exemptions are derived from ROLE_REGISTRY in oracle_generator.py
# via compile_roles() → policy/audit_policy.v1.json.  Never add names here
# directly; update ROLE_REGISTRY.resolution instead.
#
# Usage:
#   bash audit_dsvm.sh [SWIFT_ROOT]
#   SWIFT_ROOT defaults to the directory containing this script.
#
# Exit codes:
#   0 — all invariants satisfied; system is allowed to compile
#   1 — violation detected; build must halt

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWIFT_ROOT="${1:-$(dirname "$SCRIPT_DIR")}"

echo "🔒 DSVM-0 STATIC AUDIT START"
echo "   scanning: $SWIFT_ROOT"
echo "   policy:   $(dirname "$SCRIPT_DIR")/policy/audit_policy.v1.json"
echo ""

# ── 1. STATE_INIT exclusivity (op: StateConstruction) ─────────────────────────
echo "→ Checking STATE_INIT exclusivity..."

# Deny: TravelerState( constructed outside applyReducer.
# Exempt files are determined by role (bootstrap/oracle/non_audited) from
# ROLE_REGISTRY.  This grep -v pattern is generated — not hand-maintained.
if grep -Rn "TravelerState(" "$SWIFT_ROOT" --include="*.swift" \
   | grep -v "applyReducer\|func applyReducer\|//\|AppFlow.swift\|AppNavigator.swift\|DSVM0Oracle.swift\|QSEvent.swift\|QuantumStarApp.swift\|ReplayHarnessCI.swift\|ReplayHarnessDiff.swift" \
   | grep -q .; then
  echo "❌ VIOLATION: STATE_INIT op detected outside allowed roles"
  grep -Rn "TravelerState(" "$SWIFT_ROOT" --include="*.swift" \
    | grep -v "applyReducer\|func applyReducer\|//\|AppFlow.swift\|AppNavigator.swift\|DSVM0Oracle.swift\|QSEvent.swift\|QuantumStarApp.swift\|ReplayHarnessCI.swift\|ReplayHarnessDiff.swift" || true
  exit 1
fi

# Deny: travelerState = outside AppFlow.send(_:)
if grep -Rn "travelerState\s*=" "$SWIFT_ROOT" --include="*.swift" \
   | grep -v "apply(\|//\|AppFlow.swift" \
   | grep -q .; then
  echo "❌ VIOLATION: Unauthorized NonReducerMutation op detected"
  grep -Rn "travelerState\s*=" "$SWIFT_ROOT" --include="*.swift" \
    | grep -v "apply(\|//\|AppFlow.swift" || true
  exit 1
fi
echo "   ✅ TravelerState mutations confined to reducer path"

# ── 2. Rule-layer purity (no scene access) ────────────────────────────────────
echo "→ Checking rule-layer purity..."

VIEW_RULE_FILES=$(find "$SWIFT_ROOT" -name "*View.swift" -o -name "*Rule*.swift" 2>/dev/null || true)
if [ -n "$VIEW_RULE_FILES" ]; then
  if echo "$VIEW_RULE_FILES" | xargs grep -ln "entity\.isEnabled\|entity\.components" 2>/dev/null | grep -q .; then
    echo "❌ VIOLATION: Scene access (entity.isEnabled / entity.components) in rule/view layer"
    echo "$VIEW_RULE_FILES" | xargs grep -ln "entity\.isEnabled\|entity\.components" || true
    exit 1
  fi
fi
echo "   ✅ Rule layer: no forbidden scene access"

# ── 3. Event determinism (ops: TIME_READ, RANDOM_READ) ────────────────────────
echo "→ Checking event determinism..."

if grep -Rn "UUID()" "$SWIFT_ROOT" --include="*.swift" \
   | grep -v "//.*UUID()\|witness_id\|certificate_id" \
   | grep -q .; then
  echo "❌ VIOLATION: RANDOM_READ op (UUID()) — events must not carry runtime identity"
  grep -Rn "UUID()" "$SWIFT_ROOT" --include="*.swift" | grep -v "//.*UUID()" || true
  exit 1
fi

if grep -Rn "Date()" "$SWIFT_ROOT" --include="*.swift" \
   | grep -v "//.*Date()" \
   | grep -q .; then
  echo "❌ VIOLATION: TIME_READ op (Date()) — events must not carry implicit temporal context"
  grep -Rn "Date()" "$SWIFT_ROOT" --include="*.swift" | grep -v "//" || true
  exit 1
fi
echo "   ✅ Event bus: no RANDOM_READ / TIME_READ ops"

# ── 4. Projection purity (no EMIT op from read-only layer) ───────────────────
echo "→ Checking projection purity..."

if grep -Rn "emit(\|send(" "$SWIFT_ROOT" --include="*.swift" \
   | grep "projectWorld" \
   | grep -v "//" \
   | grep -q .; then
  echo "❌ VIOLATION: Projection layer emitting events (projectWorld must be pure)"
  grep -Rn "emit(\|send(" "$SWIFT_ROOT" --include="*.swift" | grep "projectWorld" | grep -v "//" || true
  exit 1
fi
echo "   ✅ Projection: no event emission"

# ── 5. Oracle presence validation ─────────────────────────────────────────────
echo "→ Checking CI oracle presence..."

ORACLE_FILE=$(find "$SWIFT_ROOT" -name "DSVM0Oracle.swift" 2>/dev/null | head -1 || true)
if [ -z "$ORACLE_FILE" ]; then
  echo "❌ VIOLATION: DSVM0Oracle.swift not found in $SWIFT_ROOT"
  echo "   Generate with: python -m src.oracle_generator"
  exit 1
fi
echo "   ✅ DSVM0Oracle.swift: $ORACLE_FILE"

HARNESS_FILE=$(find "$SWIFT_ROOT" -name "ReplayHarnessCI.swift" 2>/dev/null | head -1 || true)
if [ -z "$HARNESS_FILE" ]; then
  echo "❌ VIOLATION: ReplayHarnessCI.swift not found in $SWIFT_ROOT"
  echo "   Generate with: python -m src.oracle_generator"
  exit 1
fi
echo "   ✅ ReplayHarnessCI.swift: $HARNESS_FILE"

# ── 6. Policy artifact presence ────────────────────────────────────────────────
echo "→ Checking role policy artifacts..."

POLICY_FILE="$(dirname "$SCRIPT_DIR")/policy/audit_policy.v1.json"
if [ ! -f "$POLICY_FILE" ]; then
  echo "❌ VIOLATION: audit_policy.v1.json not found — run: python -m src.oracle_generator"
  exit 1
fi
echo "   ✅ audit_policy.v1.json: $POLICY_FILE"

# ── Result ────────────────────────────────────────────────────────────────────
echo ""
echo "✅ DSVM-0 STATIC AUDIT PASSED — system is allowed to compile"
exit 0
