#!/usr/bin/env bash
# audit_dsvm.sh — DSVM-0 Pre-Compilation Causality Gate (Phase 1 of CI pipeline)
#
# This is NOT a utility script. It is a pre-test causality gate.
# It sits above Swift, below CI, and decides whether the system is even
# allowed to become a testable object.
#
# If this script fails → nothing else executes.
#
# Generated by src/oracle_generator.py — do not edit manually.
#
# Usage:
#   bash audit_dsvm.sh [SWIFT_ROOT]
#   SWIFT_ROOT defaults to the directory containing this script (assuming
#   spatial_vm_fixtures/ lives inside the Xcode project root).
#
# Exit codes:
#   0 — all invariants satisfied; system is allowed to compile
#   1 — violation detected; build must halt

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWIFT_ROOT="${1:-$(dirname "$SCRIPT_DIR")}"

echo "🔒 DSVM-0 STATIC AUDIT START"
echo "   scanning: $SWIFT_ROOT"
echo ""

# ── 1. Reducer exclusivity ────────────────────────────────────────────────────
echo "→ Checking reducer exclusivity..."

# Ban: TravelerState( constructed outside applyReducer
# A TravelerState value may only be created inside the reducer function.
if grep -Rn "TravelerState(" "$SWIFT_ROOT" --include="*.swift" \
   | grep -v "applyReducer\|func applyReducer\|test\|spec\|//.*TravelerState(\|DSVM0Oracle\|initialState" \
   | grep -q .; then
  echo "❌ VIOLATION: Direct TravelerState construction outside reducer path"
  grep -Rn "TravelerState(" "$SWIFT_ROOT" --include="*.swift" \
    | grep -v "applyReducer\|func applyReducer\|test\|spec\|//\|DSVM0Oracle\|initialState" || true
  exit 1
fi

# Ban: `travelerState =` outside AppFlow.send(_:) which calls apply(_:)
if grep -Rn "travelerState\s*=" "$SWIFT_ROOT" --include="*.swift" \
   | grep -v "apply(\|AppFlow\.swift\|//.*travelerState" \
   | grep -q .; then
  echo "❌ VIOLATION: Unauthorized state mutation path detected"
  grep -Rn "travelerState\s*=" "$SWIFT_ROOT" --include="*.swift" \
    | grep -v "apply(\|AppFlow\.swift\|//" || true
  exit 1
fi
echo "   ✅ TravelerState mutations confined to reducer path"

# ── 2. Rule-layer purity (no scene access) ────────────────────────────────────
echo "→ Checking rule-layer purity..."

# Rule/View files (Node A, B, C) must not reference RealityKit in rule logic.
# Projections are the only legal RealityKit boundary.
VIEW_RULE_FILES=$(find "$SWIFT_ROOT" -name "*View.swift" -o -name "*Rule*.swift" 2>/dev/null || true)
if [ -n "$VIEW_RULE_FILES" ]; then
  # Check if any non-projection symbol from RealityKit leaks into rule evaluation
  if echo "$VIEW_RULE_FILES" | xargs grep -ln "entity\.isEnabled\|entity\.components" 2>/dev/null | grep -q .; then
    echo "❌ VIOLATION: Scene access (entity.isEnabled / entity.components) in rule/view layer"
    echo "$VIEW_RULE_FILES" | xargs grep -ln "entity\.isEnabled\|entity\.components" || true
    exit 1
  fi
fi
echo "   ✅ Rule layer: no forbidden scene access"

# ── 3. Event determinism (no runtime identity) ────────────────────────────────
echo "→ Checking event determinism..."

if grep -Rn "UUID()" "$SWIFT_ROOT" --include="*.swift" \
   | grep -v "//.*UUID()\|witness_id\|certificate_id" \
   | grep -q .; then
  echo "❌ VIOLATION: Runtime UUID usage detected — events must not carry runtime identity"
  grep -Rn "UUID()" "$SWIFT_ROOT" --include="*.swift" | grep -v "//.*UUID()" || true
  exit 1
fi

if grep -Rn "Date()" "$SWIFT_ROOT" --include="*.swift" \
   | grep -v "//.*Date()" \
   | grep -q .; then
  echo "❌ VIOLATION: Time dependency detected — events must not carry implicit temporal context"
  grep -Rn "Date()" "$SWIFT_ROOT" --include="*.swift" | grep -v "//" || true
  exit 1
fi
echo "   ✅ Event bus: no UUID() or Date() injection"

# ── 4. Projection safety (no side-effect writes) ──────────────────────────────
echo "→ Checking projection purity..."

# projectWorld() must not call emit/send
if grep -Rn "emit(\|send(" "$SWIFT_ROOT" --include="*.swift" \
   | grep "projectWorld" \
   | grep -v "//" \
   | grep -q .; then
  echo "❌ VIOLATION: Projection layer emitting events (projectWorld must be pure)"
  grep -Rn "emit(\|send(" "$SWIFT_ROOT" --include="*.swift" | grep "projectWorld" | grep -v "//" || true
  exit 1
fi
echo "   ✅ Projection: no event emission"

# ── 5. Oracle presence validation ─────────────────────────────────────────────
echo "→ Checking CI oracle presence..."

ORACLE_FILE=$(find "$SWIFT_ROOT" -name "DSVM0Oracle.swift" 2>/dev/null | head -1 || true)
if [ -z "$ORACLE_FILE" ]; then
  echo "❌ VIOLATION: DSVM0Oracle.swift not found in $SWIFT_ROOT"
  echo "   Generate with: python -m src.oracle_generator"
  exit 1
fi
echo "   ✅ DSVM0Oracle.swift: $ORACLE_FILE"

HARNESS_FILE=$(find "$SWIFT_ROOT" -name "ReplayHarnessCI.swift" 2>/dev/null | head -1 || true)
if [ -z "$HARNESS_FILE" ]; then
  echo "❌ VIOLATION: ReplayHarnessCI.swift not found in $SWIFT_ROOT"
  echo "   Generate with: python -m src.oracle_generator"
  exit 1
fi
echo "   ✅ ReplayHarnessCI.swift: $HARNESS_FILE"

# ── Result ────────────────────────────────────────────────────────────────────
echo ""
echo "✅ DSVM-0 STATIC AUDIT PASSED — system is allowed to compile"
exit 0
