    // GENERATED by src/oracle_generator.py — do not edit manually.
    // To regenerate: python -m src.oracle_generator
    //
    // DSVM-0 Oracle — CI Run Matrix
    //
    // State oracle commits (use for cross-run equality assertions):
    //   Run A: 3851a7fd15bf06150606e0c9455cd11fcbdd75153bf541fcd26762a8e7cf8177
//   Run B: 8e08e3956da8c551d4b580304c8d26ca71b2fd1cd42277cb4f4911383878c737
//   Run C: 3851a7fd15bf06150606e0c9455cd11fcbdd75153bf541fcd26762a8e7cf8177
//   Run D: 3851a7fd15bf06150606e0c9455cd11fcbdd75153bf541fcd26762a8e7cf8177
    //
    // Schema: dsvm0-oracle-v1

    import Foundation

    struct DSVM0Oracle {
        // MARK: Run A — ascension branch: commit_A ≠ commit_B (bifurcation from TravelerState.ascension only)
    // State oracle commit: 3851a7fd15bf06150606e0c9…
    static let runA = ReplayRun(
        id: "DSVM0-RUN-A",
        events: [
            .enterNode("neon-in-nirvana"),
            .discoverArtifact("broken-star-compass"),
            .revealLore("map-remembers"),
            .portalUnlocked("godly-dna"),
            .nodeCompleted("neon-in-nirvana"),
            .enterNode("godly-dna"),
            .chooseAscension,
            .nodeCompleted("godly-dna"),
            .enterNode("sky-high")
        ],
        expected: TravelerState(
            visitedNodes: [
            "neon-in-nirvana",
            "godly-dna",
            "sky-high"
        ],
            discoveredArtifacts: [
            "broken-star-compass"
        ],
            revealedLore: [
            "map-remembers"
        ],
            ascension: true
        )
    )
    // MARK: Run B — creation branch: commit_B ≠ commit_A; same journey, different choice
    // State oracle commit: 8e08e3956da8c551d4b58030…
    static let runB = ReplayRun(
        id: "DSVM0-RUN-B",
        events: [
            .enterNode("neon-in-nirvana"),
            .discoverArtifact("broken-star-compass"),
            .revealLore("map-remembers"),
            .portalUnlocked("godly-dna"),
            .nodeCompleted("neon-in-nirvana"),
            .enterNode("godly-dna"),
            .chooseCreation,
            .nodeCompleted("godly-dna"),
            .enterNode("sky-high")
        ],
        expected: TravelerState(
            visitedNodes: [
            "neon-in-nirvana",
            "godly-dna",
            "sky-high"
        ],
            discoveredArtifacts: [
            "broken-star-compass"
        ],
            revealedLore: [
            "map-remembers"
        ],
            ascension: false
        )
    )
    // MARK: Run C — determinism replay: identical events → commit_C == commit_A
    // State oracle commit: 3851a7fd15bf06150606e0c9…
    static let runC = ReplayRun(
        id: "DSVM0-RUN-C",
        events: [
            .enterNode("neon-in-nirvana"),
            .discoverArtifact("broken-star-compass"),
            .revealLore("map-remembers"),
            .portalUnlocked("godly-dna"),
            .nodeCompleted("neon-in-nirvana"),
            .enterNode("godly-dna"),
            .chooseAscension,
            .nodeCompleted("godly-dna"),
            .enterNode("sky-high")
        ],
        expected: TravelerState(
            visitedNodes: [
            "neon-in-nirvana",
            "godly-dna",
            "sky-high"
        ],
            discoveredArtifacts: [
            "broken-star-compass"
        ],
            revealedLore: [
            "map-remembers"
        ],
            ascension: true
        )
    )
    // MARK: Run D — idempotency: re-entry of visited nodes → commit_D == commit_A (state unchanged)
    // State oracle commit: 3851a7fd15bf06150606e0c9…
    static let runD = ReplayRun(
        id: "DSVM0-RUN-D",
        events: [
            .enterNode("neon-in-nirvana"),
            .discoverArtifact("broken-star-compass"),
            .revealLore("map-remembers"),
            .portalUnlocked("godly-dna"),
            .nodeCompleted("neon-in-nirvana"),
            .enterNode("godly-dna"),
            .chooseAscension,
            .nodeCompleted("godly-dna"),
            .enterNode("sky-high"),
            .enterNode("neon-in-nirvana"),
            .enterNode("godly-dna"),
            .enterNode("sky-high"),
            .enterNode("neon-in-nirvana")
        ],
        expected: TravelerState(
            visitedNodes: [
            "neon-in-nirvana",
            "godly-dna",
            "sky-high"
        ],
            discoveredArtifacts: [
            "broken-star-compass"
        ],
            revealedLore: [
            "map-remembers"
        ],
            ascension: true
        )
    )

        // MARK: - Export for CI harness
        static let runs: [ReplayRun] = [runA, runB, runC, runD]
    }
