// GENERATED by src/oracle_generator.py — do not edit manually.
//
// QSEvent — canonical DSVM-0 event grammar
//
// This file is derived from EVENT_SCHEMAS in oracle_generator.py.
// To add a new event: add to EVENT_SCHEMAS → python -m src.oracle_generator
// The generator updates this file, DSVM0Freeze.json (oracle_seal changes),
// and DSVM0Oracle.swift simultaneously.
//
// Current vocabulary (7 events):
//   enter_node
//   discover_artifact
//   reveal_lore
//   choose_ascension
//   choose_creation
//   node_completed
//   portal_unlocked
//
// If an event does not exist in EVENT_SCHEMAS, it cannot appear here.
// That is the grammar closure guarantee.

enum QSEvent: Equatable {
    case enterNode(nodeId: String)
    case discoverArtifact(artifactId: String)
    case revealLore(loreId: String)
    case chooseAscension
    case chooseCreation
    case nodeCompleted(nodeId: String)
    case portalUnlocked(portalId: String)
}
