// GENERATED by src/oracle_generator.py — do not edit manually.
//
// QuantumStarApp — DSVM-0 entry point
// Drop-in for Xcode alongside AppFlow.swift and AppNavigator.swift.

import SwiftUI

@main
struct QuantumStarApp: App {
    @StateObject private var appFlow = AppFlow()

    var body: some Scene {
        WindowGroup {
            AppNavigator()
                .environmentObject(appFlow)
        }
    }
}
