// GENERATED by src/oracle_generator.py — do not edit manually.
//
// DSVM-0 CI Gate Harness
// Drop-in for Xcode; wire to your QSEvent enum and TravelerState reducer.

import Foundation

// MARK: - CI Gate Failure

struct CIGateFailure: Error, CustomStringConvertible {
    let message: String
    let failingRuns: [ReplayRun]

    var description: String {
        var out = "\n❌ DSVM-0 VIOLATION: TravelerState divergence detected\n"
        out += message + "\n"
        for run in failingRuns {
            out += "\n── Run: \(run.id) ──\n"
            out += "  Expected: \(run.expected.debugDescription)\n"
            out += "  Actual:   \(run.actual?.debugDescription ?? "nil")\n"
        }
        return out
    }
}

// MARK: - CI Harness

struct ReplayHarnessCI {
    static func runCIGate() async throws {
        let runs = DSVM0Oracle.runs
        let harness = ReplayHarness()
        let results = harness.verifyDeterminism(runs: runs)

        let failing = results.filter { !$0.stateMatches }
        guard failing.isEmpty else {
            let failure = CIGateFailure(
                message: "DSVM-0 oracle divergence detected",
                failingRuns: failing
            )
            print(ReplayHarnessDiff.visualize(failure))
            throw failure
        }

        print("✅ DSVM-0 CI gate passed: \(results.count) runs, deterministic equality verified")
    }
}

// MARK: - ReplayHarness contract (implement against your app's reducer)

// final class ReplayHarness {
//     func verifyDeterminism(runs: [ReplayRun]) -> [ReplayRun] {
//         runs.map { run in
//             let final = execute(run.events)
//             return ReplayRun(id: run.id, events: run.events, expected: run.expected, actual: final)
//         }
//     }
//     private func execute(_ events: [QSEvent]) -> TravelerState {
//         var s = TravelerState()
//         for event in events {
//             let reactions = evaluate(event: event)
//             s = applyReducer(s, reactions)
//         }
//         return s
//     }
// }

// MARK: - XCTest wrapper

// import XCTest
// @MainActor
// final class ReplayHarnessTests: XCTestCase {
//     func testDSVM0_CIGate() async throws {
//         try await ReplayHarnessCI.runCIGate()
//     }
// }
