// GENERATED by src/oracle_generator.py — do not edit manually.
//
// DSVM-0 Replay Harness Diff Visualizer
// Emits state diff trees, event divergence traces, and first-point-of-failure
// localization when CI fails. Wire to your reducer for step-by-step replay.

import Foundation

struct ReplayHarnessDiff {

    // MARK: - Top-level visualizer (called by ReplayHarnessCI on failure)

    static func visualize(_ failure: CIGateFailure) -> String {
        var out = "\n❌ DSVM-0 VIOLATION: TravelerState divergence detected\n"
        out += "\n📊 State Diff Trees:\n"
        for run in failure.failingRuns {
            out += "\n── Run: \(run.id) ──\n"
            if let actual = run.actual {
                out += stateDiffTree(expected: run.expected, actual: actual)
            }
            out += "\n🔍 Event Divergence Trace:\n"
            out += eventTrace(run: run)
            out += "\n🎯 First Point of Failure:\n"
            out += firstFailure(run: run)
        }
        return out
    }

    // MARK: - State diff tree

    private static func stateDiffTree(expected: TravelerState, actual: TravelerState) -> String {
        var diff = ""
        diff += field("visitedNodes",        expected.visitedNodes.count,        actual.visitedNodes.count)
        diff += field("discoveredArtifacts",  expected.discoveredArtifacts.count, actual.discoveredArtifacts.count)
        diff += field("revealedLore",         expected.revealedLore.count,        actual.revealedLore.count)
        diff += field("ascension",            expected.ascension,                 actual.ascension)
        return diff
    }

    private static func field<T: Equatable>(_ name: String, _ exp: T, _ act: T) -> String {
        let mark = exp == act ? "  ✅" : "  ❌"
        return "\(mark) \(name): expected=\(exp), actual=\(act)\n"
    }

    // MARK: - Event divergence trace
    // Replays events one-by-one to find where actual state first diverges from expected.

    private static func eventTrace(run: ReplayRun) -> String {
        // Wire `stepReplay` to your reducer for live tracing.
        // Without it, this reports final-state divergence only.
        guard let actual = run.actual else {
            return "  (no actual state — reducer not wired)\n"
        }
        if actual == run.expected {
            return "  No divergence (state matches)\n"
        }
        return "  Final state diverges from expected (wire stepReplay for per-event trace)\n"
    }

    // MARK: - First point of failure
    // Requires stepReplay(state:event:) to be implemented.

    private static func firstFailure(run: ReplayRun) -> String {
        guard let actual = run.actual else {
            return "  (no actual state — reducer not wired)\n"
        }
        if actual == run.expected {
            return "  No failure (state matches)\n"
        }
        return "  Final ascension=\(actual.ascension), visitedNodes=\(actual.visitedNodes.count)\n"
    }

    // MARK: - Step replay hook (implement against your app's reducer)
    //
    // static func stepReplay(_ state: TravelerState, _ event: QSEvent) -> TravelerState {
    //     let reactions = evaluate(event: event)
    //     return applyReducer(state, reactions)
    // }
}
