"""
DSVM-0 CI Run Matrix Generator

Usage:
    python -m src.oracle_generator            # regenerate fixtures + Swift files
    python -m src.oracle_generator --verify   # verify frozen fixtures match current impl

Outputs (written to spatial_vm_fixtures/):
    oracle_runs.json     — frozen expected TravelerState snapshots, commits, event streams
    DSVM0Oracle.swift    — Swift oracle for drop-in Xcode integration
    ReplayHarnessCI.swift  — CI gate harness (extend for your QSEvent types)
    ReplayHarnessDiff.swift — Failure diff visualizer

The JSON fixtures are the canonical source of truth for CI.  The Swift files are
generated from the same fixture data so they stay in sync automatically.

Exit codes (--verify mode):
    0  — all fixtures match current implementation
    1  — one or more runs diverged from frozen oracle
    2  — fixture file missing or unreadable
"""
import argparse
import json
import sys
import textwrap
from pathlib import Path

from .spatial_vm_conformance import (
    run_a, run_b, run_c, run_d,
    STREAM_RUN_A, STREAM_RUN_B, STREAM_RUN_C, STREAM_RUN_D,
    RunResult,
)
from .traveler_state import TravelerState, apply_event, commit_state
from .spatial_vm_conformance import _STATE_ORACLE_RUN_ID

FIXTURES_DIR = Path(__file__).parent.parent / "spatial_vm_fixtures"
ORACLE_JSON = FIXTURES_DIR / "oracle_runs.json"
DSVM0_ORACLE_SWIFT = FIXTURES_DIR / "DSVM0Oracle.swift"
HARNESS_CI_SWIFT = FIXTURES_DIR / "ReplayHarnessCI.swift"
HARNESS_DIFF_SWIFT = FIXTURES_DIR / "ReplayHarnessDiff.swift"
APP_FLOW_SWIFT = FIXTURES_DIR / "AppFlow.swift"
APP_NAVIGATOR_SWIFT = FIXTURES_DIR / "AppNavigator.swift"
QUANTUM_STAR_APP_SWIFT = FIXTURES_DIR / "QuantumStarApp.swift"
AUDIT_SCRIPT = FIXTURES_DIR / "audit_dsvm.sh"
FREEZE_TAG = FIXTURES_DIR / "DSVM0Freeze.json"
CI_PIPELINE_SPEC = FIXTURES_DIR / "DSVM0CIPipeline.json"
QS_EVENT_SWIFT = FIXTURES_DIR / "QSEvent.swift"

# ---------------------------------------------------------------------------
# Event schema — canonical grammar definition
#
# This is the single source of truth for the event vocabulary.
# Adding a new event here and regenerating:
#   1. Updates event_vocabulary in DSVM0Freeze.json (grammar change is auditable)
#   2. Emits the new case in QSEvent.swift (Swift cannot compile unknown events)
#   3. Updates the audit script oracle-presence check
#   4. Changes oracle_seal_sha256 (boundary touch is recorded)
#
# params: [(swift_label, swift_type), ...]  — empty list for no-payload cases
# ---------------------------------------------------------------------------

EVENT_SCHEMAS: dict[str, dict] = {
    "enter_node":        {"swift_case": "enterNode",        "params": [("nodeId",      "String")]},
    "discover_artifact": {"swift_case": "discoverArtifact", "params": [("artifactId",  "String")]},
    "reveal_lore":       {"swift_case": "revealLore",       "params": [("loreId",      "String")]},
    "choose_ascension":  {"swift_case": "chooseAscension",  "params": []},
    "choose_creation":   {"swift_case": "chooseCreation",   "params": []},
    "node_completed":    {"swift_case": "nodeCompleted",    "params": [("nodeId",      "String")]},
    "portal_unlocked":   {"swift_case": "portalUnlocked",   "params": [("portalId",   "String")]},
}


def _swift_case_signature(name: str, schema: dict) -> str:
    if not schema["params"]:
        return f"case {schema['swift_case']}"
    param_str = ", ".join(f"{label}: {typ}" for label, typ in schema["params"])
    return f"case {schema['swift_case']}({param_str})"


def generate_qs_event_swift() -> str:
    cases = "\n".join(
        f"    {_swift_case_signature(name, schema)}"
        for name, schema in EVENT_SCHEMAS.items()
    )
    vocab_lines = "\n".join(f"//   {name}" for name in EVENT_SCHEMAS)
    return (
        "// GENERATED by src/oracle_generator.py — do not edit manually.\n"
        "//\n"
        "// QSEvent — canonical DSVM-0 event grammar\n"
        "//\n"
        "// This file is derived from EVENT_SCHEMAS in oracle_generator.py.\n"
        "// To add a new event: add to EVENT_SCHEMAS → python -m src.oracle_generator\n"
        "// The generator updates this file, DSVM0Freeze.json (oracle_seal changes),\n"
        "// and DSVM0Oracle.swift simultaneously.\n"
        "//\n"
        f"// Current vocabulary ({len(EVENT_SCHEMAS)} events):\n"
        f"{vocab_lines}\n"
        "//\n"
        "// If an event does not exist in EVENT_SCHEMAS, it cannot appear here.\n"
        "// That is the grammar closure guarantee.\n"
        "\n"
        "enum QSEvent: Equatable {\n"
        f"{cases}\n"
        "}\n"
    )


# ---------------------------------------------------------------------------
# JSON serialization helpers
# ---------------------------------------------------------------------------

def _state_to_dict(state: TravelerState) -> dict:
    return {
        "visited_nodes": list(state.visited_nodes),
        "discovered_artifacts": list(state.discovered_artifacts),
        "revealed_lore": list(state.revealed_lore),
        "ascension": state.ascension,
        "gene_choice_locked": state.gene_choice_locked,
        "convergence_score": state.convergence_score,
    }


def _generate_trace(events: list[dict]) -> list[dict]:
    """Step-by-step trace: state after each event in the stream."""
    s = TravelerState()
    trace = []
    for i, ev in enumerate(events):
        s = apply_event(s, ev)
        trace.append({
            "step": i,
            "event": ev,
            "state_after": _state_to_dict(s),
            "state_commit_hex": commit_state(s, _STATE_ORACLE_RUN_ID).hex(),
        })
    return trace


def _run_to_dict(result: RunResult) -> dict:
    return {
        "id": result.run_id,
        "proves": result.proves,
        "events": result.events,
        "expected_state": _state_to_dict(result.final_state),
        "state_commit_hex": result.state_commit.hex(),
        "run_commit_hex": result.commit.hex(),
        "ct0_verdict": result.ct0_verdict,
        "advisory_projection_hashes": result.projection_hashes,
        "state_trace": _generate_trace(result.events),
    }


def generate_oracle_json(results: dict[str, RunResult]) -> dict:
    return {
        "schema": "dsvm0-oracle-v1",
        "oracle_sentinel_run_id": "DSVM0-STATE-ORACLE",
        "runs": {key: _run_to_dict(r) for key, r in results.items()},
    }


# ---------------------------------------------------------------------------
# Swift code generators
# ---------------------------------------------------------------------------

def _swift_string_array(items: list[str], indent: int = 12) -> str:
    pad = " " * indent
    if not items:
        return "[]"
    inner = (",\n" + pad).join(f'"{v}"' for v in items)
    return f'[\n{pad}{inner}\n{" " * (indent - 4)}]'


def _swift_events(events: list[dict], indent: int = 12) -> str:
    pad = " " * indent
    lines = []
    for ev in events:
        t = ev["type"]
        if t == "enter_node":
            lines.append(f'.enterNode("{ev["node_id"]}")')
        elif t == "discover_artifact":
            lines.append(f'.discoverArtifact("{ev["artifact_id"]}")')
        elif t == "reveal_lore":
            lines.append(f'.revealLore("{ev["lore_id"]}")')
        elif t == "choose_ascension":
            lines.append(".chooseAscension")
        elif t == "choose_creation":
            lines.append(".chooseCreation")
        elif t == "node_completed":
            lines.append(f'.nodeCompleted("{ev["node_id"]}")')
        elif t == "portal_unlocked":
            lines.append(f'.portalUnlocked("{ev["portal_id"]}")')
    inner = (",\n" + pad).join(lines)
    return f'[\n{pad}{inner}\n{" " * (indent - 4)}]'


def generate_dsvm0_oracle_swift(results: dict[str, RunResult]) -> str:
    runs_code = []
    for label, r in results.items():
        s = r.final_state
        events_swift = _swift_events(r.events)
        nodes_swift = _swift_string_array(list(s.visited_nodes))
        arts_swift = _swift_string_array(list(s.discovered_artifacts))
        lore_swift = _swift_string_array(list(s.revealed_lore))
        ascension_val = "true" if s.ascension else "false"
        runs_code.append(f'''\
    // MARK: Run {label} — {r.proves}
    // State oracle commit: {r.state_commit.hex()[:24]}…
    static let run{label} = ReplayRun(
        id: "{r.run_id}",
        events: {events_swift},
        expected: TravelerState(
            visitedNodes: {nodes_swift},
            discoveredArtifacts: {arts_swift},
            revealedLore: {lore_swift},
            ascension: {ascension_val}
        )
    )''')

    run_refs = ", ".join(f"run{k}" for k in results)

    return textwrap.dedent(f"""\
    // GENERATED by src/oracle_generator.py — do not edit manually.
    // To regenerate: python -m src.oracle_generator
    //
    // DSVM-0 Oracle — CI Run Matrix
    //
    // State oracle commits (use for cross-run equality assertions):
    {chr(10).join(f"//   Run {k}: {r.state_commit.hex()}" for k, r in results.items())}
    //
    // Schema: dsvm0-oracle-v1

    import Foundation

    struct DSVM0Oracle {{
    {chr(10).join(runs_code)}

        // MARK: - Export for CI harness
        static let runs: [ReplayRun] = [{run_refs}]
    }}
    """)


def generate_harness_ci_swift() -> str:
    return textwrap.dedent("""\
    // GENERATED by src/oracle_generator.py — do not edit manually.
    //
    // DSVM-0 CI Gate Harness
    // Drop-in for Xcode; wire to your QSEvent enum and TravelerState reducer.

    import Foundation

    // MARK: - CI Gate Failure

    struct CIGateFailure: Error, CustomStringConvertible {
        let message: String
        let failingRuns: [ReplayRun]

        var description: String {
            var out = "\\n❌ DSVM-0 VIOLATION: TravelerState divergence detected\\n"
            out += message + "\\n"
            for run in failingRuns {
                out += "\\n── Run: \\(run.id) ──\\n"
                out += "  Expected: \\(run.expected.debugDescription)\\n"
                out += "  Actual:   \\(run.actual?.debugDescription ?? "nil")\\n"
            }
            return out
        }
    }

    // MARK: - CI Harness

    struct ReplayHarnessCI {
        static func runCIGate() async throws {
            let runs = DSVM0Oracle.runs
            let harness = ReplayHarness()
            let results = harness.verifyDeterminism(runs: runs)

            let failing = results.filter { !$0.stateMatches }
            guard failing.isEmpty else {
                let failure = CIGateFailure(
                    message: "DSVM-0 oracle divergence detected",
                    failingRuns: failing
                )
                print(ReplayHarnessDiff.visualize(failure))
                throw failure
            }

            print("✅ DSVM-0 CI gate passed: \\(results.count) runs, deterministic equality verified")
        }
    }

    // MARK: - ReplayHarness contract (implement against your app's reducer)

    // final class ReplayHarness {
    //     func verifyDeterminism(runs: [ReplayRun]) -> [ReplayRun] {
    //         runs.map { run in
    //             let final = execute(run.events)
    //             return ReplayRun(id: run.id, events: run.events, expected: run.expected, actual: final)
    //         }
    //     }
    //     private func execute(_ events: [QSEvent]) -> TravelerState {
    //         var s = TravelerState()
    //         for event in events {
    //             let reactions = evaluate(event: event)
    //             s = applyReducer(s, reactions)
    //         }
    //         return s
    //     }
    // }

    // MARK: - XCTest wrapper

    // import XCTest
    // @MainActor
    // final class ReplayHarnessTests: XCTestCase {
    //     func testDSVM0_CIGate() async throws {
    //         try await ReplayHarnessCI.runCIGate()
    //     }
    // }
    """)


def generate_quantum_star_app_swift() -> str:
    return textwrap.dedent("""\
    // GENERATED by src/oracle_generator.py — do not edit manually.
    //
    // QuantumStarApp — DSVM-0 entry point
    // Drop-in for Xcode alongside AppFlow.swift and AppNavigator.swift.

    import SwiftUI

    @main
    struct QuantumStarApp: App {
        @StateObject private var appFlow = AppFlow()

        var body: some Scene {
            WindowGroup {
                AppNavigator()
                    .environmentObject(appFlow)
            }
        }
    }
    """)


def generate_app_flow_swift() -> str:
    return textwrap.dedent("""\
    // GENERATED by src/oracle_generator.py — do not edit manually.
    //
    // AppFlow — DSVM-0 interface #2 (the only write authority for TravelerState)
    //
    // Routing is intentionally semantics-free.
    // All semantic changes MUST happen via send(_:) → reducer.

    import SwiftUI

    @MainActor
    final class AppFlow: ObservableObject {
        @Published private(set) var travelerState: TravelerState
        @Published var currentNode: CurrentNode

        init(
            initialState: TravelerState = TravelerState(),
            initialNode: CurrentNode = .neonInNirvana
        ) {
            self.travelerState = initialState
            self.currentNode = initialNode
        }

        // DSVM-0 interface #1
        func initialState() -> TravelerState { TravelerState() }

        // DSVM-0 interface #2 — single write authority for TravelerState
        func send(_ event: QSEvent) {
            travelerState = applyReducer(travelerState, event)
        }

        // Navigation-only: switches currentNode without touching TravelerState
        func navigateTo(_ node: CurrentNode) {
            currentNode = node
        }

        // DSVM-0 interface #3 (optional — for projection oracle in CI)
        func projectHash(node: String, state: TravelerState) -> String {
            // Replace with your projectWorld() implementations.
            // Must be a pure function of state — no Entity reads.
            return ""
        }
    }
    """)


def generate_app_navigator_swift() -> str:
    return textwrap.dedent("""\
    // GENERATED by src/oracle_generator.py — do not edit manually.
    //
    // AppNavigator — pure projection selector
    //
    // Navigation is a pure selection of projection, not a causality step.
    // The only causality step remains: send(event) → reducer → new TravelerState.

    import SwiftUI

    struct AppNavigator: View {
        @EnvironmentObject private var appFlow: AppFlow

        var body: some View {
            switch appFlow.currentNode {
            case .neonInNirvana:
                NeonInNirvanaView(
                    travelerState: appFlow.travelerState,
                    send: appFlow.send,
                    navigateTo: appFlow.navigateTo
                )
            case .godlyDNA:
                GodlyDNAView(
                    travelerState: appFlow.travelerState,
                    send: appFlow.send,
                    navigateTo: appFlow.navigateTo
                )
            case .skyHigh:
                SkyHighView(
                    travelerState: appFlow.travelerState,
                    send: appFlow.send,
                    navigateTo: appFlow.navigateTo
                )
            }
        }
    }

    enum CurrentNode: String, Equatable {
        case neonInNirvana = "neon-in-nirvana"
        case godlyDNA      = "godly-dna"
        case skyHigh       = "sky-high"
    }

    // MARK: - Minimal view signatures
    // Views receive TravelerState as a value and can only call send(event).
    // They must not mutate TravelerState directly.

    struct NeonInNirvanaView: View {
        let travelerState: TravelerState
        let send: (QSEvent) -> Void
        let navigateTo: (CurrentNode) -> Void

        var body: some View {
            // Wire your existing NeonInNirvanaView content here.
            // Example: Button("Enter Godly DNA") {
            //     send(.onNodeCompleted(nodeId: "neon-in-nirvana"))
            //     navigateTo(.godlyDNA)
            // }
            Text("Node A: Neon In Nirvana")
        }
    }

    struct GodlyDNAView: View {
        let travelerState: TravelerState
        let send: (QSEvent) -> Void
        let navigateTo: (CurrentNode) -> Void

        var body: some View {
            // Wire your existing GodlyDNAView content here.
            // Branch choice example:
            // Button("Ascend") { send(.onChoiceAscension); navigateTo(.skyHigh) }
            // Button("Create") { send(.onChoiceCreation); navigateTo(.skyHigh) }
            Text("Node B: Godly DNA")
        }
    }

    struct SkyHighView: View {
        let travelerState: TravelerState
        let send: (QSEvent) -> Void
        let navigateTo: (CurrentNode) -> Void

        var body: some View {
            // Wire your existing SkyHighView content here.
            // Temporal drift: projectWorld() reads travelerState, never scene state.
            Text("Node C: Sky High")
        }
    }
    """)


def generate_audit_script() -> str:
    return textwrap.dedent("""\
    #!/usr/bin/env bash
    # audit_dsvm.sh — DSVM-0 Pre-Compilation Causality Gate (Phase 1 of CI pipeline)
    #
    # This is NOT a utility script. It is a pre-test causality gate.
    # It sits above Swift, below CI, and decides whether the system is even
    # allowed to become a testable object.
    #
    # If this script fails → nothing else executes.
    #
    # Generated by src/oracle_generator.py — do not edit manually.
    #
    # Usage:
    #   bash audit_dsvm.sh [SWIFT_ROOT]
    #   SWIFT_ROOT defaults to the directory containing this script (assuming
    #   spatial_vm_fixtures/ lives inside the Xcode project root).
    #
    # Exit codes:
    #   0 — all invariants satisfied; system is allowed to compile
    #   1 — violation detected; build must halt

    set -euo pipefail
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    SWIFT_ROOT="${1:-$(dirname "$SCRIPT_DIR")}"

    echo "🔒 DSVM-0 STATIC AUDIT START"
    echo "   scanning: $SWIFT_ROOT"
    echo ""

    # ── 1. Reducer exclusivity ────────────────────────────────────────────────────
    echo "→ Checking reducer exclusivity..."

    # Ban: TravelerState( constructed outside applyReducer
    # A TravelerState value may only be created inside the reducer function.
    if grep -Rn "TravelerState(" "$SWIFT_ROOT" --include="*.swift" \\
       | grep -v "applyReducer\\|func applyReducer\\|test\\|spec\\|//.*TravelerState(" \\
       | grep -q .; then
      echo "❌ VIOLATION: Direct TravelerState construction outside reducer path"
      grep -Rn "TravelerState(" "$SWIFT_ROOT" --include="*.swift" \\
        | grep -v "applyReducer\\|func applyReducer\\|test\\|spec\\|//" || true
      exit 1
    fi

    # Ban: `travelerState =` outside AppFlow.send(_:) which calls apply(_:)
    if grep -Rn "travelerState\\s*=" "$SWIFT_ROOT" --include="*.swift" \\
       | grep -v "apply(\\|AppFlow\\.swift\\|//.*travelerState" \\
       | grep -q .; then
      echo "❌ VIOLATION: Unauthorized state mutation path detected"
      grep -Rn "travelerState\\s*=" "$SWIFT_ROOT" --include="*.swift" \\
        | grep -v "apply(\\|AppFlow\\.swift\\|//" || true
      exit 1
    fi
    echo "   ✅ TravelerState mutations confined to reducer path"

    # ── 2. Rule-layer purity (no scene access) ────────────────────────────────────
    echo "→ Checking rule-layer purity..."

    # Rule/View files (Node A, B, C) must not reference RealityKit in rule logic.
    # Projections are the only legal RealityKit boundary.
    VIEW_RULE_FILES=$(find "$SWIFT_ROOT" -name "*View.swift" -o -name "*Rule*.swift" 2>/dev/null || true)
    if [ -n "$VIEW_RULE_FILES" ]; then
      # Check if any non-projection symbol from RealityKit leaks into rule evaluation
      if echo "$VIEW_RULE_FILES" | xargs grep -ln "entity\\.isEnabled\\|entity\\.components" 2>/dev/null | grep -q .; then
        echo "❌ VIOLATION: Scene access (entity.isEnabled / entity.components) in rule/view layer"
        echo "$VIEW_RULE_FILES" | xargs grep -ln "entity\\.isEnabled\\|entity\\.components" || true
        exit 1
      fi
    fi
    echo "   ✅ Rule layer: no forbidden scene access"

    # ── 3. Event determinism (no runtime identity) ────────────────────────────────
    echo "→ Checking event determinism..."

    if grep -Rn "UUID()" "$SWIFT_ROOT" --include="*.swift" \\
       | grep -v "//.*UUID()\\|witness_id\\|certificate_id" \\
       | grep -q .; then
      echo "❌ VIOLATION: Runtime UUID usage detected — events must not carry runtime identity"
      grep -Rn "UUID()" "$SWIFT_ROOT" --include="*.swift" | grep -v "//.*UUID()" || true
      exit 1
    fi

    if grep -Rn "Date()" "$SWIFT_ROOT" --include="*.swift" \\
       | grep -v "//.*Date()" \\
       | grep -q .; then
      echo "❌ VIOLATION: Time dependency detected — events must not carry implicit temporal context"
      grep -Rn "Date()" "$SWIFT_ROOT" --include="*.swift" | grep -v "//" || true
      exit 1
    fi
    echo "   ✅ Event bus: no UUID() or Date() injection"

    # ── 4. Projection safety (no side-effect writes) ──────────────────────────────
    echo "→ Checking projection purity..."

    # projectWorld() must not call emit/send
    if grep -Rn "emit(\\|send(" "$SWIFT_ROOT" --include="*.swift" \\
       | grep "projectWorld" \\
       | grep -v "//" \\
       | grep -q .; then
      echo "❌ VIOLATION: Projection layer emitting events (projectWorld must be pure)"
      grep -Rn "emit(\\|send(" "$SWIFT_ROOT" --include="*.swift" | grep "projectWorld" | grep -v "//" || true
      exit 1
    fi
    echo "   ✅ Projection: no event emission"

    # ── 5. Oracle presence validation ─────────────────────────────────────────────
    echo "→ Checking CI oracle presence..."

    ORACLE_FILE=$(find "$SWIFT_ROOT" -name "DSVM0Oracle.swift" 2>/dev/null | head -1 || true)
    if [ -z "$ORACLE_FILE" ]; then
      echo "❌ VIOLATION: DSVM0Oracle.swift not found in $SWIFT_ROOT"
      echo "   Generate with: python -m src.oracle_generator"
      exit 1
    fi
    echo "   ✅ DSVM0Oracle.swift: $ORACLE_FILE"

    HARNESS_FILE=$(find "$SWIFT_ROOT" -name "ReplayHarnessCI.swift" 2>/dev/null | head -1 || true)
    if [ -z "$HARNESS_FILE" ]; then
      echo "❌ VIOLATION: ReplayHarnessCI.swift not found in $SWIFT_ROOT"
      echo "   Generate with: python -m src.oracle_generator"
      exit 1
    fi
    echo "   ✅ ReplayHarnessCI.swift: $HARNESS_FILE"

    # ── Result ────────────────────────────────────────────────────────────────────
    echo ""
    echo "✅ DSVM-0 STATIC AUDIT PASSED — system is allowed to compile"
    exit 0
    """)


def generate_freeze_tag(results: dict[str, RunResult], oracle_json: dict) -> dict:
    """DSVM-0 v1.0 freeze tag — versioned snapshot of the entire constraint system."""
    import hashlib as _hl

    oracle_bytes = json.dumps(oracle_json, sort_keys=True).encode()
    seal = _hl.sha256(oracle_bytes).hexdigest()

    return {
        "schema": "dsvm0-freeze-v1",
        "version": "1.0",
        "sealed": True,
        "oracle_seal_sha256": seal,
        "oracle_sentinel_run_id": "DSVM0-STATE-ORACLE",
        "state_oracle_commits": {
            label: r.state_commit.hex() for label, r in results.items()
        },
        "event_vocabulary": list(EVENT_SCHEMAS.keys()),
        "event_schemas": {
            name: {
                "swift_case": schema["swift_case"],
                "params": [{"label": lbl, "type": typ} for lbl, typ in schema["params"]],
            }
            for name, schema in EVENT_SCHEMAS.items()
        },
        "committed_state_fields": [
            "visited_nodes", "discovered_artifacts", "revealed_lore",
            "ascension", "gene_choice_locked",
        ],
        "negative_invariants": {
            "N1": "TravelerState mutation must only appear inside applyReducer",
            "N2": "Projection functions must not read Entity/scene state as input",
            "N3": "Events must not carry implicit temporal context (Date, UUID at emission)",
            "N4": "Reducer must not emit events, call send(), or trigger async work",
        },
        "conformance_axes": {
            "A_vs_B": "bifurcation: commit_A ≠ commit_B (ascension flip from TravelerState only)",
            "C":      "determinism: identical events → identical state commit",
            "D":      "idempotency: re-entry of visited nodes leaves state unchanged",
        },
        "run_proves": {label: r.proves for label, r in results.items()},
    }


def generate_ci_pipeline_spec(results: dict[str, RunResult], freeze: dict) -> dict:
    """
    Full CI pipeline spec — execution order as law.
    Defines phase order, failure propagation, and deterministic logging format.
    """
    return {
        "schema": "dsvm0-ci-pipeline-v1",
        "oracle_seal_sha256": freeze["oracle_seal_sha256"],
        "failure_mode": "fail-closed",
        "phases": [
            {
                "id": 1,
                "name": "static-audit",
                "description": "grep-level architectural invariant check (pre-compilation)",
                "command": "bash spatial_vm_fixtures/audit_dsvm.sh $SWIFT_ROOT",
                "on_fail": "halt — skip all subsequent phases",
                "checks": list(freeze["negative_invariants"].keys()),
                "invariant_violation_exits_with": 1,
            },
            {
                "id": 2,
                "name": "swift-build",
                "description": "normal Swift compilation",
                "command": "xcodebuild build -scheme QuantumStarApp",
                "on_fail": "halt",
                "depends_on": [1],
            },
            {
                "id": 3,
                "name": "dsvm0-ci-gate",
                "description": "XCTest: ReplayHarnessTests.testDSVM0_CIGate()",
                "command": "swift test --filter ReplayHarnessTests",
                "on_fail": "emit ReplayHarnessDiff output; exit 1",
                "oracle_runs": list(results.keys()),
                "depends_on": [1, 2],
            },
            {
                "id": 4,
                "name": "python-oracle-verify",
                "description": "verify Python oracle matches frozen fixtures (cross-language)",
                "command": "python -m src.oracle_generator --verify",
                "on_fail": "emit state diff per run; exit 1",
                "depends_on": [1],
            },
            {
                "id": 5,
                "name": "oracle-staleness-check",
                "description": "detect if oracle fixtures need regeneration after code changes",
                "command": "python -m src.oracle_generator && git diff --exit-code spatial_vm_fixtures/",
                "on_fail": "exit 1 with diff output; fix: python -m src.oracle_generator && commit",
                "depends_on": [4],
            },
        ],
        "failure_propagation": {
            "phase_1_fail": "structural impossibility — fix before any execution",
            "phase_2_fail": "compilation error — fix before behavioral testing",
            "phase_3_fail": "behavioral divergence — ReplayHarnessDiff shows first-failing event",
            "phase_4_fail": "cross-language divergence — Python oracle and Swift diverged",
            "phase_5_fail": "fixture staleness — regenerate oracle and commit",
        },
        "deterministic_log_format": {
            "phase_pass": "✅ [phase-name] PASS",
            "phase_fail": "❌ [phase-name] FAIL: [reason]",
            "divergence":  "❌ DSVM-0 VIOLATION: TravelerState divergence detected",
            "first_event": "🎯 First Divergence: step N — {event}",
            "state_diff":  "  [✅|❌] field: oracle=X, actual=Y",
            "gate_pass":   "✅ DSVM-0 CI gate passed: N runs, deterministic equality verified",
        },
        "xcode_build_phase_order": [
            "1. Run Script: bash ${SRCROOT}/spatial_vm_fixtures/audit_dsvm.sh ${SRCROOT}",
            "2. Compile Sources",
            "3. Link Binary",
            "4. Run Script: swift test --filter ReplayHarnessTests (optional post-build)",
        ],
        "github_actions_jobs": [
            "dsvm0-gate (runs phases 1, 4, 5)",
            "Phases 2-3 run inside Xcode build system",
        ],
    }


def generate_harness_diff_swift() -> str:
    return textwrap.dedent("""\
    // GENERATED by src/oracle_generator.py — do not edit manually.
    //
    // DSVM-0 Replay Harness Diff Visualizer
    // Emits state diff trees, event divergence traces, and first-point-of-failure
    // localization when CI fails. Wire to your reducer for step-by-step replay.

    import Foundation

    struct ReplayHarnessDiff {

        // MARK: - Top-level visualizer (called by ReplayHarnessCI on failure)

        static func visualize(_ failure: CIGateFailure) -> String {
            var out = "\\n❌ DSVM-0 VIOLATION: TravelerState divergence detected\\n"
            out += "\\n📊 State Diff Trees:\\n"
            for run in failure.failingRuns {
                out += "\\n── Run: \\(run.id) ──\\n"
                if let actual = run.actual {
                    out += stateDiffTree(expected: run.expected, actual: actual)
                }
                out += "\\n🔍 Event Divergence Trace:\\n"
                out += eventTrace(run: run)
                out += "\\n🎯 First Point of Failure:\\n"
                out += firstFailure(run: run)
            }
            return out
        }

        // MARK: - State diff tree

        private static func stateDiffTree(expected: TravelerState, actual: TravelerState) -> String {
            var diff = ""
            diff += field("visitedNodes",        expected.visitedNodes.count,        actual.visitedNodes.count)
            diff += field("discoveredArtifacts",  expected.discoveredArtifacts.count, actual.discoveredArtifacts.count)
            diff += field("revealedLore",         expected.revealedLore.count,        actual.revealedLore.count)
            diff += field("ascension",            expected.ascension,                 actual.ascension)
            return diff
        }

        private static func field<T: Equatable>(_ name: String, _ exp: T, _ act: T) -> String {
            let mark = exp == act ? "  ✅" : "  ❌"
            return "\\(mark) \\(name): expected=\\(exp), actual=\\(act)\\n"
        }

        // MARK: - Event divergence trace
        // Replays events one-by-one to find where actual state first diverges from expected.

        private static func eventTrace(run: ReplayRun) -> String {
            // Wire `stepReplay` to your reducer for live tracing.
            // Without it, this reports final-state divergence only.
            guard let actual = run.actual else {
                return "  (no actual state — reducer not wired)\\n"
            }
            if actual == run.expected {
                return "  No divergence (state matches)\\n"
            }
            return "  Final state diverges from expected (wire stepReplay for per-event trace)\\n"
        }

        // MARK: - First point of failure
        // Requires stepReplay(state:event:) to be implemented.

        private static func firstFailure(run: ReplayRun) -> String {
            guard let actual = run.actual else {
                return "  (no actual state — reducer not wired)\\n"
            }
            if actual == run.expected {
                return "  No failure (state matches)\\n"
            }
            return "  Final ascension=\\(actual.ascension), visitedNodes=\\(actual.visitedNodes.count)\\n"
        }

        // MARK: - Step replay hook (implement against your app's reducer)
        //
        // static func stepReplay(_ state: TravelerState, _ event: QSEvent) -> TravelerState {
        //     let reactions = evaluate(event: event)
        //     return applyReducer(state, reactions)
        // }
    }
    """)


# ---------------------------------------------------------------------------
# Verify mode: load frozen JSON and compare against current impl
# ---------------------------------------------------------------------------

def _format_divergence(label: str, result: RunResult, frozen: dict) -> str:
    lines = [f"\n── Run {label}: {result.run_id} ──"]
    frozen_commit = frozen["state_commit_hex"]
    actual_commit = result.state_commit.hex()
    if frozen_commit != actual_commit:
        lines.append(f"  state_commit DIVERGED")
        lines.append(f"    frozen:  {frozen_commit[:32]}…")
        lines.append(f"    actual:  {actual_commit[:32]}…")

    frozen_state = frozen["expected_state"]
    actual_state = _state_to_dict(result.final_state)
    for field in ("visited_nodes", "discovered_artifacts", "revealed_lore", "ascension", "convergence_score"):
        fv, av = frozen_state.get(field), actual_state.get(field)
        mark = "✅" if fv == av else "❌"
        if fv != av:
            lines.append(f"  {mark} {field}: frozen={fv!r}, actual={av!r}")
    return "\n".join(lines)


def verify_fixtures(results: dict[str, RunResult]) -> int:
    if not ORACLE_JSON.exists():
        print(f"ERROR: oracle fixture not found: {ORACLE_JSON}", file=sys.stderr)
        print("Run `python -m src.oracle_generator` to generate it.", file=sys.stderr)
        return 2

    try:
        frozen = json.loads(ORACLE_JSON.read_text())
    except Exception as exc:
        print(f"ERROR: cannot read oracle fixture: {exc}", file=sys.stderr)
        return 2

    failures = []
    for label, result in results.items():
        frozen_run = frozen["runs"].get(label)
        if frozen_run is None:
            failures.append(f"Run {label} missing from frozen fixtures.")
            continue
        if result.state_commit.hex() != frozen_run["state_commit_hex"]:
            failures.append(_format_divergence(label, result, frozen_run))

    if failures:
        print("❌ DSVM-0 CI GATE FAIL: oracle divergence detected\n")
        for f in failures:
            print(f)
        return 1

    print("✅ DSVM-0 CI gate passed: all runs match frozen oracle")
    return 0


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="DSVM-0 CI Run Matrix Generator")
    parser.add_argument("--verify", action="store_true",
                        help="Verify frozen fixtures; exit 1 on divergence, 2 on missing")
    args = parser.parse_args()

    results = {"A": run_a(), "B": run_b(), "C": run_c(), "D": run_d()}

    if args.verify:
        sys.exit(verify_fixtures(results))

    # Generate mode: write all fixture files
    FIXTURES_DIR.mkdir(exist_ok=True)

    oracle = generate_oracle_json(results)
    ORACLE_JSON.write_text(json.dumps(oracle, indent=2))
    print(f"✅ Written: {ORACLE_JSON}")

    DSVM0_ORACLE_SWIFT.write_text(generate_dsvm0_oracle_swift(results))
    print(f"✅ Written: {DSVM0_ORACLE_SWIFT}")

    HARNESS_CI_SWIFT.write_text(generate_harness_ci_swift())
    print(f"✅ Written: {HARNESS_CI_SWIFT}")

    HARNESS_DIFF_SWIFT.write_text(generate_harness_diff_swift())
    print(f"✅ Written: {HARNESS_DIFF_SWIFT}")

    QUANTUM_STAR_APP_SWIFT.write_text(generate_quantum_star_app_swift())
    print(f"✅ Written: {QUANTUM_STAR_APP_SWIFT}")

    APP_FLOW_SWIFT.write_text(generate_app_flow_swift())
    print(f"✅ Written: {APP_FLOW_SWIFT}")

    APP_NAVIGATOR_SWIFT.write_text(generate_app_navigator_swift())
    print(f"✅ Written: {APP_NAVIGATOR_SWIFT}")

    QS_EVENT_SWIFT.write_text(generate_qs_event_swift())
    print(f"✅ Written: {QS_EVENT_SWIFT}")

    audit_script = generate_audit_script()
    AUDIT_SCRIPT.write_text(audit_script)
    AUDIT_SCRIPT.chmod(0o755)
    print(f"✅ Written: {AUDIT_SCRIPT}")

    freeze = generate_freeze_tag(results, oracle)
    FREEZE_TAG.write_text(json.dumps(freeze, indent=2))
    print(f"✅ Written: {FREEZE_TAG}")

    pipeline = generate_ci_pipeline_spec(results, freeze)
    CI_PIPELINE_SPEC.write_text(json.dumps(pipeline, indent=2))
    print(f"✅ Written: {CI_PIPELINE_SPEC}")

    print("\nState oracle commits:")
    for label, r in results.items():
        print(f"  Run {label}: {r.state_commit.hex()}")
    print(f"\nFreeze seal (SHA256 of oracle): {freeze['oracle_seal_sha256'][:24]}…")


if __name__ == "__main__":
    main()
